### PR TITLE
Bumped CADVISOR_TAG to 0.16.0

### LINKED ISSUE #8: Upgrade cadvisor to 0.15.0 or greater
We've just deployed a BYON running Ubuntu 15.04 and the metrics container is stuck in a reboot loop.

I've done some digging, and it seems like the invocation of `/cadvisor` is not doing so well. It seems like the [issue](https://github.com/google/cadvisor/issues/666) has been reported and [fixed](https://github.com/google/cadvisor/pull/746) in the upstream cadvisor repository, specifically version `0.15.0` or newer. 

Can we bump the CADVISOR_TAG to `0.15.0` (or latest `0.16.0`)?

### PR DESCRIPTION
**Pull request by phindmarsh**
Fixes #8 

I've built a replacement image using this Dockerfile and deployed it to our Ubuntu 15.04 node and it works as expected, just copied the ENV of the native `tutum/metrics` container that is flapping.

### CODE REVIEW

**Comment by tifayuki** [comment]
@pchico83 I pushed the image with cadvisor 0.16.0 on staging, can you test if it is compatible with tutum server application?

**Comment by fermayo** [comment]
We have this in staging already - will get to master as soon as we pass our internal testing. Thanks @phindmarsh

**Comment by phindmarsh** [comment]
Has this landed yet? Our metrics container is still flapping on our Ubuntu 15.04 BYO node. Just wondering if its still because of this or if something else has been introduced.

**Comment by fermayo** [comment]
It will probably be published today to production

**Pull request closed without merging**
